name: "Bug Report"
description: Create a report to fix a current bug or issue
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        If you're experiencing a problem, please provide as much information as possible to fix it.

  - type: input
    id: bug-summary
    attributes:
      label: Bug Summary
      description: A clear and concise description of what the bug is.
      placeholder: "e.g., The system crashes when trying to load..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. Scroll down to '...'\n4. See error"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "e.g., The system should..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment, such as FPGA model, software version, etc.
      placeholder: "e.g., Xilinx FPGA, Software version 1.2.3"
    validations:
      required: true
