name: "Documentation Request"
description: Request improvements or additions to the documentation
title: "[Docs]: "
labels: ["documentation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Sugests things to be added to the wiki, google docs, diagrams...

  - type: input
    id: doc-topic
    attributes:
      label: Documentation Topic
      description: What topic needs documentation?
      placeholder: "e.g., Vivado Synthesis of overlays..."
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Describe the problem or confusion the existing documentation might have caused.
      placeholder: "e.g., The current documentation does not cover..."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: Provide your suggestions for improvement.
      placeholder: "e.g., Including a section on..."
    validations:
      required: false
