name: Vivado builds

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main]
    types: [review_requested, synchronize]

jobs:
  Clone_Repo:
    runs-on: Vivado2023.02
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

  Build_kria_i2c_dcmi_dpu:
    runs-on: Vivado2023.02
    needs: Clone_Repo
    steps:
      - name: Build_Vivado_from_tcl
        shell: bash
        run: |
          cd ~/AVHBAC_GitHub/actions-runner/AVHBAC_runner_out/main/main/src/fpga/overlays/kria_i2c_dcmi_dpu/
          make clean
          make xsa XILINX_VIVADO=/opt/Xilinx/Vivado/2023.2

  Upload_bitstream_to_Artifacts:
  - name: Upload_bitstream_to_Artifacts
    uses: actions/upload-artifact@v4
    with:
      name: bitstream
      path: ~/AVHBAC_GitHub/actions-runner/AVHBAC_runner_out/main/main/src/fpga/overlays/kria_i2c_dcmi_dpu/project/FPGA_Prosthetic.bit
