name: Vivado builds

on:
  push:
    branches:
      - main
  pull_request:
    types: [review_requested]
    branches:
      - main

jobs:
  build:
    runs-on: Vivado2023.02

    steps:
    - name: Checkout code
      uses: actions/checkout@v2